name: flutter_circle_flags_svg
description: Flutter Circle Flags SVG
version: 0.0.3
homepage: https://github.com/iamriajul/flutter_circle_flags_svg

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/flags/