name: flutter_circle_flags_svg
description: Flutter Circle Flags SVG, It is a Flutter package that provides a widget to display a circle flag of a country.
version: 1.0.3
homepage: https://github.com/iamriajul/flutter_circle_flags_svg

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/flags/